global:
  image:
    repository: 253016134262.dkr.ecr.us-west-2.amazonaws.com/happeningatm
    tag: "e438e4ba298b19d7938941f3ba9e7d3c6d4e8b96"
  deployed_url: happeningatm-dev.opensourcesanjose.org
  eks_shared_environment: prod
  doppler_secret_ref: happeningatm-dev-doppler-secrets

frontend:
  replicaCount: 1
  cpu:
    requests: 50m
    limit: 1000m
  memory:
    requests: 50Mi
    limit: 1024Mi
  port: 80

backend:
  replicaCount: 1
  command: ["npm", "run", "start"]
  cpu:
    requests: 100m
    limit: 1000m
  memory:
    requests: 150Mi
    limit: 1024Mi
  port: 3002

graphql:
  replicaCount: 1
  command: ["npm", "run", "start"]
  cpu:
    requests: 100m
    limit: 1000m
  memory:
    requests: 150Mi
    limit: 1024Mi
  port: 3000

serviceaccount:
  create: false

vpa:
  create: false
