global:
  image:
    repository: 253016134262.dkr.ecr.us-west-2.amazonaws.com/eimmigrate
    tag: "465448d3f16947635df8bb91dfba108434f93fd1"
  deployed_url: eimmigrate-stage.opensourcesanjose.org
  eks_shared_environment: prod
  doppler_secret_ref: eimmigrate-stage-doppler-secrets

frontend:
  replicaCount: 1
  cpu:
    requests: 50m
    limit: 1000m
  memory:
    requests: 50Mi
    limit: 1024Mi
  port: 3000

backend:
  replicaCount: 1
  command: ["npm", "run", "start"]
  cpu:
    requests: 100m
    limit: 1000m
  memory:
    requests: 150Mi
    limit: 1024Mi
  port: 3001

serviceaccount:
  create: false

vpa:
  create: false
