global:
  image:
    repository: 253016134262.dkr.ecr.us-west-2.amazonaws.com/eimmigrate
    tag: "dc2f7927724ef4c1372d87beb9bb6bd976eb1239"
  deployed_url: eimmigrate.opensourcesanjose.org
  eks_shared_environment: prod
  doppler_secret_ref: eimmigrate-prod-doppler-secrets

frontend:
  replicaCount: 1
  cpu:
    requests: 50m
    limit: 1000m
  memory:
    requests: 50Mi
    limit: 1024Mi
  port: 3000

backend:
  replicaCount: 1
  command: ["npm", "run", "start"]
  cpu:
    requests: 100m
    limit: 1000m
  memory:
    requests: 150Mi
    limit: 1024Mi
  port: 3001

serviceaccount:
  create: false

vpa:
  create: false
