apiVersion: v2
name: happeningatm-dev
description: This Chart deploys happeningatm-dev
type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
- name: happeningatm
  version: 0.0.1
  repository: file://../../../../../charts/happeningatm
