---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: eimmigrate
    namespace: argocd
spec:
    generators:
        - list:
              elements: 
                #   - applicationName: heartofthevalley-dev
                #     project: heartofthevalley
                #     namespace: heartofthevalley-dev
                #     path: deployments/heartofthevalley/environments/dev/argocd
                #     destinationServer: https://kubernetes.default.svc
                  - applicationName: eimmigrate-stage
                    project: dev
                    namespace: eimmigrate-stage
                    path: deployments/eimmigrate/environments/stage/argocd
                    destinationServer: https://kubernetes.default.svc
                #   - applicationName: heartofthevalley-prod
                #     project: heartofthevalley
                #     namespace: heartofthevalley-prod
                #     path: deployments/heartofthevalley/environments/prod/argocd
                #     destinationServer: https://kubernetes.default.svc
    template:
        metadata:
            name: '{{applicationName}}'
        spec:
            project: '{{project}}'
            source:
                repoURL: https://github.com/codeforsanjose/gitops.git
                targetRevision: main
                path: '{{path}}'
                helm:
                    valueFiles:
                        - values.yaml
            destination:
                server: '{{destinationServer}}'
                namespace: '{{namespace}}'
            syncPolicy:
                syncOptions:
                    - CreateNamespace=true
    ignoreApplicationDifferences:
        - jqPathExpressions:
              - .spec.source.helm.parameters
