---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: happeningatm
    namespace: argocd
spec:
    generators:
        - list:
              elements:
                  - applicationName: happeningatm-dev
                    project: dev
                    namespace: happeningatm-dev
                    path: deployments/happeningatm/environments/dev/argocd
                    destinationServer: https://kubernetes.default.svc
                  - applicationName: happeningatm-stage
                    # TODO: Create and use new ArgoCD Project `happeningatm`
                    project: dev
                    namespace: happeningatm-stage
                    path: deployments/happeningatm/environments/stage/argocd
                    destinationServer: https://kubernetes.default.svc
    template:
        metadata:
            name: '{{applicationName}}'
        spec:
            project: '{{project}}'
            source:
                repoURL: https://github.com/codeforsanjose/kubernetes.git
                targetRevision: main
                path: '{{path}}'
                helm:
                    valueFiles:
                        - values.yaml
            destination:
                server: '{{destinationServer}}'
                namespace: '{{namespace}}'
            syncPolicy:
                syncOptions:
                    - CreateNamespace=true
    ignoreApplicationDifferences:
        - jqPathExpressions:
              - .spec.source.helm.parameters
